from .counterpart_repository import CounterpartRepository
from .investment_approach_repository import InvestmentApproachRepository
from .law_repository import LawRepository
from .type_project_repository import TypeProjectRepository
from .category_counterpart_repository import CategoryCounterpartRepository
from .relationship_category_counterparts_repository import (
    RelationshipCategoryCounterpartsRepository,
)
from .abginvest_tpproj_lei_repository import AbginvestTpprojLeiRepository
from .type_file_repository import TypeFileRepository
from .thematic_repository import ThematicRepository
from .benefit_categorization_repository import BenefitCategorizationRepository
from .benefit_categorization_type_repository import BenefitCategorizationTypeRepository
from .abginvest_tpproj_lei_contrpart_repository import (
    AbginvestTpprojLeiContrpartRepository,
)
from .legal_representative_repository import LegalRepresentativeRepository
