services:
  hexagonal-python:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - hexagonal-python-api
    profiles: [ prod ]

  hexagonal-python-api:
    image: postgres
    ports:
      - "3006:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "app_bank" # Define o nome do banco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
