from .counterpart import Counterpart
from .investment_approach import InvestmentApproach
from .law import Law
from .type_project import TypeProject
from .category_counterpart import CategoryCounterpart
from .relationship_category_counterparts import RelationshipCategoryCounterparts
from .abginvest_tpproj_lei import AbginvestTpprojLei
from .type_file import TypeFile
from .thematic import Thematic
from .benefit_categorization_type import BenefitCategorizationType
from .benefit_categorization import BenefitCategorization
from .abginvest_tpproj_lei_contrpart import AbginvestTpprojLeiContrpart
from .proposal import Proposal
from .proposal_beneficiary import ProposalBeneficiary
from .proposal_beneficiary_categorization import ProposalBeneficiaryCategorization
from .proposal_sponsor import ProposalSponsor
from .proposal_meta import ProposalMeta
from .city import City
from .neighborhood import Neighborhood
from .street import Street
from .proposal_execution_location import ProposalExecutionLocation
from .proponent import Proponent
from .partnership_history import PartnershipHistory
from .project_contact_point import ProjectContactPoint
from .project_history import ProjectHistory
from .goal_history import GoalHistory
from .legal_representative import LegalRepresentative
from .supply_history import SupplyHistory
from .proposal_file import ProposalFile
from .proposal_milestone import ProposalMilestone
from .proposal_thematic import ProposalThematic
from .proposal_investment_type_law import ProposalInvestmentTypeLaw
from .proposal_counterpart import ProposalCounterpart
